main:
  push:
    - ifModify:
        - "!(learning-weekly.xml)"
      stages:
        - name: generate rss
          script: |
            ./gorss --root ./docs > learning-weekly.xml

        - name: set token
          imports: https://cnb.cool/eryajf/build-env/-/blob/main/env.yaml
          image: tencentcom/git-set-credential:latest
          settings:
            userName: ${CNB_TOKEN_USER_NAME}
            userEmail: ${CNB_COMMITTER_EMAIL}
            loginUserName: ${CNB_TOKEN_USER_NAME}
            loginPassword: ${CNB_TOKEN}

        - name: commit
          image: tencentcom/git-commit:latest
          settings:
            add:
              - learning-weekly.xml
            commitMessage: "commit by ci"
            pushCurrent: true

        - name: sync to github
          image: tencentcom/git-sync
          imports: https://cnb.cool/eryajf/build-env/-/blob/main/env.yaml
          settings:
            target_url: https://github.com/eryajf/Learning-Weekly.git
            auth_type: https
            git_email: 'github-actions[bot]@users.noreply.github.com'
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            branch: main